version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-nodejs-sample-codebuild
hooks:
BeforeInstall:
   - location: deployment_scripts/after_install.sh
      timeout: 100
 AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 100
      
  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 100
      
  
