version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/aws-nodejs-sample-codebuild
hooks:
 
 BeforeInstall:
     echo "starting BeforeInstallation"
     location: deployment_scripts/before_install.sh
      timeout: 300
      runas: root
      echo " finished before install"
 
 AfterInstall:
    - location: deployment_scripts/after_install.sh
      timeout: 100
      
  ApplicationStart:
    - location: deployment_scripts/start_server.sh
      timeout: 100
      
  
